spring:
  shardingsphere:
    datasource:
      # ??????????????????????????+?????
      names: db0,db1
      # ????????????
      db0:
        # ??????????????HikariDataSource
        type: com.zaxxer.hikari.HikariDataSource
        # ?????
        driver-class-name: com.mysql.cj.jdbc.Driver
        # ???????
        jdbc-url: jdbc:mysql://127.0.0.1:3306/yyds
        username: root
        password: lyh701721
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://127.0.0.1:3306/yyds1
        username: root
        password: lyh701721
#    rules:
#      sharding:
#        tables:
#          test:
#            actual-data-nodes: db0.test_$->{0..1}
#            #???????????????????table-strategy???database-strategy
#            table-strategy:
#              #??????????
#              standard:
#                sharding-column: id
#                sharding-algorithm-name: my-alg
#        sharding-algorithms:
#          my-alg:
#            #????????INLINE?????????????????
#            type: INLINE
#            props:
#              #???????????2??????????
#              #???????????????test_???????????????
#              #???????MOD??????
#              algorithm-expression: test_$->{id % 2}
#              #???????????????????????????????????????????
#              #??????????????????
#              allow-range-query-with-inline-sharding: true
    rules:
      #??????
      readwrite-splitting:
        data-sources:
          #?????
          user-db:
            #?????????Dynamic????????auto-aware-data-source-name??????
            type: Static
            props:
              #??????????
              write-data-source-name: db0
              #?????????????
              read-data-source-names: db1
              #????????????
              load-balancer-name: my-load
        load-balancers:
          #??????????
          my-load:
            type: ROUND_ROBIN
      sharding:
        tables:
          test:
            actual-data-nodes: db0.test,db1.test
            #??????????
            database-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: my-alg
            #??????????????
            key-generate-strategy:
              column: id
              key-generator-name: my-gen
        key-generators:
          #???????????????
          my-gen:
            #??????
            type: SNOWFLAKE
            props:
              #????ID???????
              worker-id: 666
        sharding-algorithms:
          my-alg:
            type: MOD
            props:
              sharding-count: 2
    props:
    #?????????????
      sql-show: true
